version: 2.1

jobs:
  build:
    docker: # Use docker executor
      - image: nixos/nix:2.18.9-arm64 # Specify your Docker image in a list
    resource_class: arm.large
    environment:
      CACHIX_NAME: zen-browser
    steps:
      - run:
          name: Install CircleCI CLI
          command: nix-env -iA nixpkgs.circleci
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash
            cachix use $CACHIX_NAME
            cachix authtoken $CACHIX_AUTH_TOKEN
      - checkout
      - run:
          name: Build and Push
          command: |
            nix build --extra-experimental-features nix-command --extra-experimental-features flakes --json --accept-flake-config \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push zen-browser

workflows:
  build:
    jobs:
      - build
