version: 2.1

jobs:
  build:
    docker:
      image: nixos/nix:current
      resource_class: arm.large
      environment:
        CACHIX_NAME: zen-browser
    steps:
      - checkout
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA nixpkgs.cachix nixpkgs.bash
            cachix use $CACHIX_NAME
            cachix authtoken $CACHIX_AUTH_TOKEN
      - run:
          name: Build and Push
          command: |
            nix build --extra-experimental-features nix-command --extra-experimental-features flakes --json --accept-flake-config \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push zen-browser

workflows:
  build:
    jobs:
      - build
